// <auto-generated />
using System;
using ChargerInfo.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChargerInfo.API.Migrations
{
    [DbContext(typeof(ChargerInfoContext))]
    partial class ChargerInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChargerInfo.API.Entities.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChargerStationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("PowerInVolt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Charger");
                });

            modelBuilder.Entity("ChargerInfo.API.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChargerId");

                    b.Property<DateTime>("SessionStartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2 ")
                        .HasDefaultValue(new DateTime(2019, 5, 29, 13, 2, 20, 26, DateTimeKind.Local).AddTicks(8899));

                    b.Property<DateTime>("SessionStopTime")
                        .HasColumnType("datetime2 ");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ChargerId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("ChargerInfo.API.Entities.Session", b =>
                {
                    b.HasOne("ChargerInfo.API.Entities.Charger", "Charger")
                        .WithMany("Sessions")
                        .HasForeignKey("ChargerId")
                        .HasConstraintName("ForeignKey_Session_Charger")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
